"""TerraVista — Train the territorial-risk RandomForest model.

Trains a RandomForestClassifier on the synthetic dataset (generated by
`generator.py`) to predict the 3-level `risk_class` (HEALTHY/ATTENTION/CRITICAL).
Evaluation emphasizes **recall on the CRITICAL class** — the costliest error is
a missed critical parcel (undetected fire/drought/crop-loss risk).

The trained model is serialized to `models/terra_risk.joblib` together with the
feature ordering and class mapping, so the backend can load and infer without
re-deriving metadata.

Usage:
    python train.py                 # generate data if missing, train, save
    python train.py --regenerate    # force-regenerate the synthetic dataset

Author: Gabriel Mule (RM 560586)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    recall_score,
)
from sklearn.model_selection import train_test_split

from generator import CLASS_NAMES, FEATURE_COLUMNS, TARGET_COLUMN, generate

HERE = Path(__file__).resolve().parent
DATA_PATH = HERE / "data" / "territory_samples.csv"
MODEL_PATH = HERE / "models" / "terra_risk.joblib"


def load_or_generate(regenerate: bool) -> pd.DataFrame:
    """Load the synthetic dataset, generating it if missing or forced."""
    if regenerate or not DATA_PATH.exists():
        print("[train] Generating synthetic dataset...")
        df = generate()
        DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(DATA_PATH, index=False)
        print(f"[train] Saved dataset → {DATA_PATH}")
    else:
        df = pd.read_csv(DATA_PATH)
        print(f"[train] Loaded dataset ({len(df)} rows) ← {DATA_PATH}")
    return df


def train(df: pd.DataFrame) -> RandomForestClassifier:
    """Train and evaluate the RandomForest classifier."""
    X = df[FEATURE_COLUMNS]
    y = df[TARGET_COLUMN]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=5,
        class_weight="balanced",  # counter the intentional class imbalance
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    target_names = [CLASS_NAMES[i] for i in sorted(CLASS_NAMES)]
    print("\n[train] Classification report (test set):")
    print(classification_report(y_test, y_pred, target_names=target_names, digits=3))

    print("[train] Confusion matrix (rows=true, cols=pred):")
    print(confusion_matrix(y_test, y_pred))

    critical = 2  # CRITICAL class index
    rec_critical = recall_score(y_test, y_pred, labels=[critical], average="macro")
    macro_f1 = f1_score(y_test, y_pred, average="macro")
    print(f"\n[train] Recall (CRITICAL): {rec_critical:.3f}")
    print(f"[train] Macro F1:          {macro_f1:.3f}")

    # Feature importances for interpretability.
    importances = sorted(
        zip(FEATURE_COLUMNS, model.feature_importances_),
        key=lambda kv: kv[1],
        reverse=True,
    )
    print("\n[train] Feature importances:")
    for name, imp in importances:
        print(f"  {name:18s} {imp:.3f}")

    return model


def save(model: RandomForestClassifier) -> None:
    """Serialize the model with metadata needed by the backend."""
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    bundle = {
        "model": model,
        "feature_columns": FEATURE_COLUMNS,
        "class_names": CLASS_NAMES,
        "version": "1.0.0",
    }
    joblib.dump(bundle, MODEL_PATH)
    print(f"\n[train] Saved model bundle → {MODEL_PATH}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train TerraVista risk model.")
    parser.add_argument(
        "--regenerate",
        action="store_true",
        help="Force-regenerate the synthetic dataset before training.",
    )
    args = parser.parse_args()

    df = load_or_generate(args.regenerate)
    model = train(df)
    save(model)
    print("\n[train] Done.")


if __name__ == "__main__":
    main()
